/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menubar;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class menuuuus extends javax.swing.JFrame {

    /**
     * Creates new form menuuuus
     */
    public menuuuus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuventana = new javax.swing.JMenu();
        menuColores = new javax.swing.JMenu();
        itemMenuColorVentana1 = new javax.swing.JMenuItem();
        itemMenuColorVentana2 = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        itemMenuSalir = new javax.swing.JMenuItem();
        menulabel = new javax.swing.JMenu();
        menuLabelColores = new javax.swing.JMenu();
        itemMenuColorLabel1 = new javax.swing.JMenuItem();
        itemMenuColorLabel2 = new javax.swing.JMenuItem();
        menuImagen = new javax.swing.JMenu();
        itemMenuImagen1 = new javax.swing.JMenuItem();
        itemMenuImagen2 = new javax.swing.JMenuItem();
        menuabout = new javax.swing.JMenu();
        itemMenuCreador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        menuventana.setText("Ventana");

        menuColores.setText("Spider-man");

        itemMenuColorVentana1.setText("Spider_man");
        itemMenuColorVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorVentana1ActionPerformed(evt);
            }
        });
        menuColores.add(itemMenuColorVentana1);

        itemMenuColorVentana2.setText("Spider-man");
        menuColores.add(itemMenuColorVentana2);

        menuventana.add(menuColores);
        menuventana.add(separador1);

        itemMenuSalir.setText("Spider_man");
        itemMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirActionPerformed(evt);
            }
        });
        menuventana.add(itemMenuSalir);

        jMenuBar1.add(menuventana);

        menulabel.setText("Label");

        menuLabelColores.setText("jMenu1");

        itemMenuColorLabel1.setText("jMenuItem1");
        menuLabelColores.add(itemMenuColorLabel1);

        itemMenuColorLabel2.setText("jMenuItem2");
        menuLabelColores.add(itemMenuColorLabel2);

        menulabel.add(menuLabelColores);

        menuImagen.setText("jMenu1");

        itemMenuImagen1.setText("jMenuItem1");
        itemMenuImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuImagen1ActionPerformed(evt);
            }
        });
        menuImagen.add(itemMenuImagen1);

        itemMenuImagen2.setText("jMenuItem2");
        menuImagen.add(itemMenuImagen2);

        menulabel.add(menuImagen);

        jMenuBar1.add(menulabel);

        menuabout.setText("about");

        itemMenuCreador.setText("jMenuItem1");
        itemMenuCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCreadorActionPerformed(evt);
            }
        });
        menuabout.add(itemMenuCreador);

        jMenuBar1.add(menuabout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuColorVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorVentana1ActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.decode("378A6A"));
    }//GEN-LAST:event_itemMenuColorVentana1ActionPerformed

    private void itemMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemMenuSalirActionPerformed

    private void itemMenuCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCreadorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Carlos Yahir Espino");
    }//GEN-LAST:event_itemMenuCreadorActionPerformed

    private void itemMenuImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuImagen1ActionPerformed
        // TODO add your handling code here:
        URL imageurl = getClass().getResource("imagen.webp");
        ImageIcon nuevoIcono = new ImageIcon(imageurl);
        label.setIcon(nuevoIcono);
    }//GEN-LAST:event_itemMenuImagen1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuuuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuuuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuuuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuuuus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuuuus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuColorLabel1;
    private javax.swing.JMenuItem itemMenuColorLabel2;
    private javax.swing.JMenuItem itemMenuColorVentana1;
    private javax.swing.JMenuItem itemMenuColorVentana2;
    private javax.swing.JMenuItem itemMenuCreador;
    private javax.swing.JMenuItem itemMenuImagen1;
    private javax.swing.JMenuItem itemMenuImagen2;
    private javax.swing.JMenuItem itemMenuSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel label;
    private javax.swing.JMenu menuColores;
    private javax.swing.JMenu menuImagen;
    private javax.swing.JMenu menuLabelColores;
    private javax.swing.JMenu menuabout;
    private javax.swing.JMenu menulabel;
    private javax.swing.JMenu menuventana;
    private javax.swing.JPopupMenu.Separator separador1;
    // End of variables declaration//GEN-END:variables
}
